server:
  port: ${AUTH_SERVICE_PORT:8082}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

user-service:
  base-url: ${USER_SERVICE_URL:http://user-service:8081}

jwt:
  secret: ${JWT_SECRET:MY_SUPER_SECRET_KEY_123456789012345678901234}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
