spring:
  application:
    name: api-gateway
  cloud:
    gateway: 
      # globalcors:
        # corsConfigurations:
        #   "[/**]":
        #     allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
        #     allowedMethods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
        #     allowedHeaders: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
        #     allowCredentials: ${CORS_ALLOW_CREDENTIALS:true}
        #     maxAge: ${CORS_MAX_AGE:3600}
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8082}
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8081}
          predicates:
            - Path=/api/users/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8083}
          predicates:
            - Path=/api/verify/**

server:
  port: ${GATEWAY_PORT:8080}

auth:
  service-url: ${AUTH_SERVICE_URL:http://auth-service:8082}
